---
version: 0.2

phases:
  install:
      commands:
        - echo "Install jq:"
        - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
  pre_build:
    commands:
      - echo "Configuring AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
  build:
    commands:
      - echo "Building..."
      - cd my-app
      - mvn compile
      - java -cp target/classes com.mycompany.app.App
  post_build:
    commands:
      - echo "Do fancy post-build stuff right here `date`"
      - ls -alR .

# artifacts:
#   files: 
#     - my-app/target/classes/com.mycompany.app.App